# Generated by Django 4.2.25 on 2025-10-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
